baseURL: "https://jonot.me/"
title: Jonot's Blog
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Jonot's Blog
  description: "A blog for Jonot"
  keywords: [Blog, Portfolio]
  author: Me
  DateFormat: "2006-01-02"

  ShowReadingTime: true
  ShowRssButtonInSectionTermList: true

  homeInfoParams:
    Title: Jonot's Blog
    Content: A place to put random stuff that I think of

  socialIcons:
    - name: "github"
      url: "https://github.com/jonot-cyber"
